version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
