name: Build Docker Image and Push to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out to app
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push to Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Dockerfile
          push: true
          tags: rahildocker1/demo-application-uni-web:latest
          