name: Build Docker Image and Push to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out to app
        uses: actions/checkout@v3

      - name: Push To Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rahildocker1/demo-applicsation-uni-web
          tags: latest, ${{ github.run_number }}
          